### ISSUE TITLE
Correção de Exercício

### ISSUE THREAD

**Issue by emersonsrv** [lucianaa/pesquisaoperacional#1]
Boa noite professora! Estava estudando o método simplex e notei que há um erro em um exercício resolvido na aula 3 (o segundo exemplo resolvido do método simplex). Na última tabela deste exercício, na posição correspondente à linha Z, coluna S1, o valor correto seria 3/4 e não 1 (e, portanto, na linha  C-Z, -3/4 e não -1). Comunico pois acredito que seria adequada a correção, impedindo uma outra pessoa que venha a estudar o material de se perder na solução do problema.
Atenciosamente.

**Comment by lucianaa** [comment]
Olá Emerson, realmente há esse erro nesse problema. Gostaria de ver como você chegou na tabela final, porque suspeito que pode haver mais de um erro. É possível?

**Comment by lucianaa** [comment]
Emerson, coloquei no github a resolução da questão 2 da prova. Se tiver alguma dúvida, me procure na próxima aula, ok?

**Comment by emersonsrv** [comment]
Ok. Muito obrigado Luciana!
